2020-01-12 14:06:04,497 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 14:06:25,155 ERROR: Exception on /edit_profile [POST] [in c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Niki4\Microblog\microblog\app\routes.py", line 101, in edit_profile
    db.session.commit()
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1036, in commit
    self.transaction.commit()
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 503, in commit
    self._prepare_impl()
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 482, in _prepare_impl
    self.session.flush()
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2479, in flush
    self._flush(objects)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2577, in _flush
    flush_context.execute()
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 236, in save_obj
    update,
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\niki4\tinkoff_education\po\final_project\microblog\venv\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('Nikita', "I'am dummy programmer! DEbug", 3)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-01-12 14:11:09,070 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 16:32:51,076 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 16:33:09,994 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 17:42:55,969 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 18:01:20,060 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 18:03:58,210 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 18:19:09,438 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 18:21:32,859 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 18:28:44,148 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 18:36:48,837 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 18:39:26,208 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 18:41:41,271 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 18:43:48,601 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 18:49:08,766 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 18:55:12,289 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 18:58:42,834 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 19:11:11,892 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 19:16:22,427 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 19:44:48,285 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 20:56:52,643 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 21:03:46,914 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 21:09:27,177 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 21:10:31,131 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 21:42:17,213 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 21:43:16,453 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-12 22:01:02,758 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:46]
2020-01-15 00:26:50,581 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:51]
2020-01-15 00:45:38,912 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:51]
2020-01-15 00:46:53,597 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:51]
2020-01-15 00:47:41,039 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:51]
2020-01-15 01:07:39,120 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:51]
2020-01-15 01:40:03,848 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:51]
2020-01-15 01:48:50,126 INFO: Microblog startup [in C:\Users\Niki4\Microblog\microblog\app\__init__.py:51]
